package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"cloud.google.com/go/storage"
	"github.com/iuriikogan/autonomous-game-assist-cli/pkg/gcp"
	"github.com/spf13/cobra"
)

var (
	downloadSession string
	downloadBucket  string
	downloadDir     string

	newStorageClient = gcp.NewStorageClient
)

var downloadCmd = &cobra.Command{
	Use:   "download",
	Short: "Download generated assets from GCS for a specific session",
	Long:  `Downloads synthesized WAV foley files and Unreal Engine automation scripts generated by the agent during a session to a local directory.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx := cmd.Context()

		if downloadSession == "" {
			return fmt.Errorf("session ID is required (use --session)")
		}

		if downloadBucket == "" {
			downloadBucket = os.Getenv("GCS_BUCKET")
			if downloadBucket == "" {
				return fmt.Errorf("GCS bucket is required (use --bucket flag or GCS_BUCKET env var)")
			}
		}

		// Initialize Storage Client
		storageClient, err := newStorageClient(ctx)
		if err != nil {
			return fmt.Errorf("failed to initialize GCS client: %w", err)
		}
		defer storageClient.Close()

		// Create target local directory if it doesn't exist
		if err := os.MkdirAll(downloadDir, 0755); err != nil {
			return fmt.Errorf("failed to create download directory: %w", err)
		}

		// Define the target objects and their local filenames
		targets := []struct {
			objectName string
			localName  string
		}{
			{
				objectName: fmt.Sprintf("audio/foley_%s.wav", downloadSession),
				localName:  fmt.Sprintf("foley_%s.wav", downloadSession),
			},
			{
				objectName: fmt.Sprintf("scripts/unreal_assist_%s.py", downloadSession),
				localName:  fmt.Sprintf("unreal_assist_%s.py", downloadSession),
			},
			{
				objectName: fmt.Sprintf("scripts/unreal_assist_%s.cpp", downloadSession),
				localName:  fmt.Sprintf("unreal_assist_%s.cpp", downloadSession),
			},
		}

		downloadedCount := 0
		for _, target := range targets {
			localPath := filepath.Join(downloadDir, target.localName)
			fmt.Printf("Downloading gs://%s/%s to %s...\n", downloadBucket, target.objectName, localPath)

			reader, err := storageClient.DownloadObject(ctx, downloadBucket, target.objectName)
			if err != nil {
				if errors.Is(err, storage.ErrObjectNotExist) {
					fmt.Printf("File gs://%s/%s does not exist, skipping.\n", downloadBucket, target.objectName)
					continue
				}
				return fmt.Errorf("failed to download %s: %w", target.objectName, err)
			}

			// Write local file
			localFile, err := os.Create(localPath)
			if err != nil {
				reader.Close()
				return fmt.Errorf("failed to create local file %s: %w", localPath, err)
			}

			_, err = io.Copy(localFile, reader)
			localFile.Close()
			reader.Close()
			if err != nil {
				return fmt.Errorf("failed to write local file %s: %w", localPath, err)
			}

			fmt.Printf("Successfully downloaded %s\n", target.localName)
			downloadedCount++
		}

		if downloadedCount == 0 {
			return fmt.Errorf("no assets found for session %s in bucket %s", downloadSession, downloadBucket)
		}

		fmt.Printf("Downloaded %d assets successfully to %s!\n", downloadedCount, downloadDir)
		return nil
	},
}

func init() {
	downloadCmd.Flags().StringVar(&downloadSession, "session", "", "The session ID or job ID to download deliverables for (required)")
	downloadCmd.Flags().StringVar(&downloadBucket, "bucket", "", "The GCS bucket name (defaults to GCS_BUCKET env var)")
	downloadCmd.Flags().StringVar(&downloadDir, "dir", "./deliverables", "The local directory to save downloaded deliverables to")
	rootCmd.AddCommand(downloadCmd)
}
